name: Pack and release the dataset and repository

# Controls when the workflow will run
on:
  # Triggers the workflow on pushing new tags
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2.4.0
      - name: Zip the Corpus folder
        run: zip -r Corpus.zip Corpus/*
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Corpus.zip
